name       : libsamplerate
version    : 0.1.8
release    : 2
source     :
    - http://www.mega-nerd.com/SRC/libsamplerate-0.1.8.tar.gz : 93b54bdf46d5e6d2354b7034395fe329c222a966790de34520702bb9642f1c06
license    : GPL-3.0
summary    : libsamplerate is a Sample Rate Converter for audio.
description: |
    libsamplerate is a Sample Rate Converter for audio.
builddeps  :
    - pkgconfig(sndfile)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
