name       : libsamplerate
version    : 0.1.9
release    : 4
source     :
    - http://www.mega-nerd.com/SRC/libsamplerate-0.1.9.tar.gz : 0a7eb168e2f21353fb6d84da152e4512126f7dc48ccb0be80578c565413444c1
license    : GPL-3.0
summary    : libsamplerate is a Sample Rate Converter for audio.
component  : multimedia.library
description: |
    libsamplerate is a Sample Rate Converter for audio.
emul32     : yes
builddeps  :
    - pkgconfig32(sndfile)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
